import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "https://esm.sh/resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface ScanEmailRequest {
  email: string;
  scanSummary: {
    domainsScanned: number;
    threatsFound: number;
    timestamp: string;
    threatResults: Array<{
      domain: string;
      score: number;
      threats: string[];
    }>;
  };
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { email, scanSummary }: ScanEmailRequest = await req.json();

    if (!email || !scanSummary) {
      throw new Error("Email and scanSummary are required");
    }

    const threatRows = scanSummary.threatResults
      .map(
        (r) => `
      <tr style="border-bottom: 1px solid #e2e8f0;">
        <td style="padding: 12px; font-weight: 600;">${r.domain}</td>
        <td style="padding: 12px; text-align: center;">
          <span style="background: ${r.score < 20 ? "#ef4444" : r.score < 40 ? "#fb923c" : "#facc15"}20; color: ${r.score < 20 ? "#ef4444" : r.score < 40 ? "#fb923c" : "#facc15"}; padding: 4px 10px; border-radius: 6px; font-weight: 700;">${r.score}</span>
        </td>
        <td style="padding: 12px; font-size: 13px; color: #64748b;">${r.threats.join(", ")}</td>
      </tr>`
      )
      .join("");

    const emailHTML = `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background-color: #f8fafc;">
  <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
    <div style="text-align: center; margin-bottom: 30px;">
      <h1 style="color: #0f172a; margin: 0; font-size: 22px;">📅 Scheduled Scan Report</h1>
      <p style="color: #64748b; margin: 8px 0 0;">TrustGuard Daily Monitoring</p>
    </div>
    
    <div style="background: white; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); overflow: hidden; margin-bottom: 20px;">
      <div style="background: ${scanSummary.threatsFound > 0 ? "#ef4444" : "#22c55e"}; padding: 20px; text-align: center;">
        <h2 style="color: white; margin: 0; font-size: 18px;">
          ${scanSummary.threatsFound > 0 ? `⚠️ ${scanSummary.threatsFound} Threat${scanSummary.threatsFound > 1 ? "s" : ""} Detected` : "✅ All Clear"}
        </h2>
      </div>
      <div style="padding: 24px;">
        <div style="display: flex; justify-content: space-around; text-align: center; margin-bottom: 20px;">
          <div>
            <p style="margin: 0; color: #64748b; font-size: 12px;">DOMAINS SCANNED</p>
            <p style="margin: 4px 0 0; font-size: 24px; font-weight: 700; color: #0f172a;">${scanSummary.domainsScanned}</p>
          </div>
          <div>
            <p style="margin: 0; color: #64748b; font-size: 12px;">THREATS FOUND</p>
            <p style="margin: 4px 0 0; font-size: 24px; font-weight: 700; color: ${scanSummary.threatsFound > 0 ? "#ef4444" : "#22c55e"};">${scanSummary.threatsFound}</p>
          </div>
        </div>
        <p style="color: #64748b; font-size: 13px; text-align: center;">Scan completed: ${new Date(scanSummary.timestamp).toLocaleString()}</p>
      </div>
    </div>

    ${
      scanSummary.threatResults.length > 0
        ? `
    <div style="background: white; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); overflow: hidden; margin-bottom: 20px;">
      <div style="padding: 16px 24px; border-bottom: 1px solid #e2e8f0;">
        <h3 style="margin: 0; color: #0f172a; font-size: 16px;">🔍 Threat Details</h3>
      </div>
      <table style="width: 100%; border-collapse: collapse;">
        <thead>
          <tr style="background: #f8fafc;">
            <th style="padding: 12px; text-align: left; font-size: 12px; color: #64748b;">Domain</th>
            <th style="padding: 12px; text-align: center; font-size: 12px; color: #64748b;">Score</th>
            <th style="padding: 12px; text-align: left; font-size: 12px; color: #64748b;">Threats</th>
          </tr>
        </thead>
        <tbody>${threatRows}</tbody>
      </table>
    </div>`
        : ""
    }

    <div style="text-align: center; padding: 20px;">
      <p style="color: #64748b; font-size: 12px;">This report was generated by TrustGuard Daily Monitoring</p>
    </div>
  </div>
</body>
</html>`;

    const emailResponse = await resend.emails.send({
      from: "TrustGuard <onboarding@resend.dev>",
      to: [email],
      subject: `📅 Daily Scan: ${scanSummary.threatsFound} threat${scanSummary.threatsFound !== 1 ? "s" : ""} found across ${scanSummary.domainsScanned} domains`,
      html: emailHTML,
    });

    return new Response(
      JSON.stringify({ success: true, data: emailResponse }),
      { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  } catch (error: any) {
    console.error("Error sending scheduled scan email:", error);
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  }
};

serve(handler);
